### ISSUE TITLE
lower AP than Resnet backbone in my training

### ISSUE THREAD

**Issue by cxx921656591** [youngwanLEE/vovnet-detectron2#7]
Hi! Thank you for your great work. I wanted to improve [Densepose](https://github.com/facebookresearch/detectron2/tree/master/projects/DensePose) project in detectron2/projects by replacing resnet-fpn backbone with vovnet, but during training I always get lower results than the original resnet backbone. One of the two results and the command I used is as below:
**python train_net.py --config-file configs/densepose_rcnn_R_50_FPN_s1x_legacy.yaml SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.001 (the original one)**
results:
[03/12 13:05:36 d2.evaluation.testing]: copypaste: Task: bbox
[03/12 13:05:36 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[03/12 13:05:36 d2.evaluation.testing]: copypaste: 53.1516,84.5066,57.3643,26.5924,51.5737,66.5134
[03/12 13:05:36 d2.evaluation.testing]: copypaste: Task: densepose_gps
[03/12 13:05:36 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APm,APl
[03/12 13:05:36 d2.evaluation.testing]: copypaste: 44.6044,83.1504,43.4994,38.4582,46.2426
[03/12 13:05:36 d2.evaluation.testing]: copypaste: Task: densepose_gpsm
[03/12 13:05:36 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APm,APl
[03/12 13:05:36 d2.evaluation.testing]: copypaste: 48.4785,86.5655,50.8903,40.1852,50.2448
[03/12 13:05:36 d2.utils.events]:  eta: 0:00:00  iter: 129999  total_loss: 2.144  loss_cls: 0.104  loss_box_reg: 0.153  loss_densepose_U: 0.444  loss_densepose_V: 0.487  loss_densepose_I: 0.176  loss_densepose_S: 0.648  loss_rpn_cls: 0.011  loss_rpn_loc: 0.021  time: 0.4843  data_time: 0.0164  lr: 0.000010  max_mem: 2939M

**python train_net.py --config-file configs/densepose_rcnn_R_50_FPN_s1x_legacy.yaml SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0001   (the backbone replaced one)**
results:
[03/15 06:48:25 d2.evaluation.testing]: copypaste: Task: bbox
[03/15 06:48:25 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[03/15 06:48:25 d2.evaluation.testing]: copypaste: 50.5212,83.5444,52.5758,22.3658,48.5157,64.9114
[03/15 06:48:25 d2.evaluation.testing]: copypaste: Task: densepose_gps
[03/15 06:48:25 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APm,APl
[03/15 06:48:25 d2.evaluation.testing]: copypaste: 41.6630,82.0449,37.6683,31.7831,43.3619
[03/15 06:48:25 d2.evaluation.testing]: copypaste: Task: densepose_gpsm
[03/15 06:48:25 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APm,APl
[03/15 06:48:25 d2.evaluation.testing]: copypaste: 46.4402,86.1345,45.5157,35.2128,48.2686
[03/15 06:48:25 d2.utils.events]:  eta: 0:00:00  iter: 269999  total_loss: 2.757  loss_cls: 0.075  loss_box_reg: 0.136  loss_densepose_U: 0.707  loss_densepose_V: 0.751  loss_densepose_I: 0.215  loss_densepose_S: 0.635  loss_rpn_cls: 0.008  loss_rpn_loc: 0.010  time: 0.2863  data_time: 0.0129  lr: 0.000001  max_mem: 4289M

the changes I've made in Base-DensePose-RCNN-FPN.yaml:
```
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_vovnet_fpn_backbone"
    FREEZE_AT: 0
    #NAME: "build_resnet_fpn_backbone"
  VOVNET:
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  #RESNETS:
    #OUT_FEATURES: ["res2", "res3", "res4", "res5"]

  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
    #IN_FEATURES: ["res2", "res3", "res4", "res5"]
```
and in densepose_rcnn_R_50_FPN_s1x_legacy.yaml:
```
_BASE_: "Base-DensePose-RCNN-FPN.yaml"
MODEL:
  #WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  #RESNETS:
    #DEPTH: 50
  WEIGHTS: "vovnet39_ese_detectron2.pth"#"https://www.dropbox.com/s/rptgw6stppbiw1u/vovnet19_ese_detectron2.pth?dl=1"
  VOVNET:
    CONV_BODY : "V-39-eSE"

  ROI_DENSEPOSE_HEAD:
    NUM_COARSE_SEGM_CHANNELS: 15
    POOLER_RESOLUTION: 14
    HEATMAP_SIZE: 56
    INDEX_WEIGHTS: 2.0
    PART_WEIGHTS: 0.3
    POINT_REGRESSION_WEIGHTS: 0.1
    DECODER_ON: False
SOLVER:
  BASE_LR: 0.002
  #MAX_ITER: 130000
  #STEPS: (100000, 120000)
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "checkpoints/MRCN-V2-39-3x"
```
Have I done something wrong? Like unsuitble learning rates or others? I've been deeply impressed by how your backbone can imporve a model's AP, so could you tell me how to train this new backbone in order to get higher results? Thanks a lot in advance!
